#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the Alpine.js sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# The Docker services.
services:
  # The Alpine.js app container
  alpinejs:
    # https://hub.docker.com/_/nginx
    image: nginx:alpine
    container_name: ${APP_CONTAINER_NAME:-alpinejs_app}
    networks:
      - local
    ports:
      - ${APP_PORT:-80}:80
    # Map the app container exposed port to the host port.
    volumes:
      - .${CODE_DIR:-/code}:/usr/share/nginx/html

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-alpinejs_local}"
