#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the Node.js sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# Docker services
services:
  # The Node.js app container
  node:
    # https://hub.docker.com/_/node
    image: node:latest
    container_name: ${APP_CONTAINER_NAME:-node_app}
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-80}:80
    tty: true
    volumes:
      - .${CODE_DIR:-/code}:/app
    working_dir: /app
    # Start the Node.js webserver.
    # https://nodejs.org/api/cli.html#command-line-api
    command: ["node", "app.js"]

# Docker networks
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-node_local}"
